path:
      demand_train: 'data/train_kaggle.csv'
      demand_test: 'data/test_kaggle.csv'
      sub_sample: 'data/submission_sample.csv'
      models: 'models'
      predictions: 'data/predictions'

feature_generation:
      lags: [7, 7, 14, 31, 41]
      rolls: [1, 3, 7, 7, 7]

model:
      target: 'Demand'
      drop_columns: ['SKU_id','Demand','Store_id']

constant:
      predict_sku: 'SKU_id'
      date_col: 'Date'